version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=kronoos_user
      - POSTGRES_PASSWORD=kronoos_password
      - POSTGRES_DB=kronoos_fullstack_challenge_db
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: